import Head from "next/head";

import { useAccount } from "wagmi";

import { Flex, Text } from "@chakra-ui/react";

import Layout from "@components/Layout";
import Proposals from "@components/Proposals";

export default function Home() {
  const { address, isConnected } = useAccount();

  return (
    <>
      <Head>
        <title>Voting App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Flex direction="column" p="2rem" alignItems="center" width="100%">
          {isConnected ? (
            <Text as="b" fontSize="lg">
              {" "}
              <Proposals />
            </Text>
          ) : (
            <Text as="b" fontSize="lg">
              Merci de vous connecter à votre wallet
            </Text>
          )}
        </Flex>
      </Layout>
    </>
  );
}
